baseURL = 'https://kampffrosch94.github.io/'
languageCode = 'en-us'
title = 'KampffroschÂ´s blog'

[module]
  [[module.imports]]
    path = "github.com/AmazingRise/hugo-theme-diary"

[markup.goldmark.renderer]
  unsafe = true
